"""Authenticated local-command application boundary."""

from app.local_command.gateway import LocalCommandApplicationGateway
from app.local_command.models import (
    LOCAL_COMMAND_TEXT_MAX_LENGTH,
    WORKSPACE_ID_MAX_LENGTH,
    LocalCommandApplicationError,
    LocalCommandApplicationErrorCode,
    LocalCommandApplicationRequest,
    LocalCommandApplicationResult,
    LocalCommandApplicationRoute,
    LocalCommandProjection,
    LocalCommandProjectionKind,
    LocalKnowledgeFindProjection,
    LocalKnowledgeProjection,
    LocalKnowledgeProjectionOperation,
    LocalKnowledgeReadProjection,
    LocalKnowledgeRecordKind,
    LocalKnowledgeRecordProjection,
    LocalKnowledgeStoreProjection,
    LocalListAddProjection,
    LocalListProjection,
    LocalListProjectionOperation,
    LocalListReadProjection,
    application_error,
)

__all__ = [
    "LOCAL_COMMAND_TEXT_MAX_LENGTH",
    "WORKSPACE_ID_MAX_LENGTH",
    "LocalCommandApplicationError",
    "LocalCommandApplicationErrorCode",
    "LocalCommandApplicationGateway",
    "LocalCommandApplicationRequest",
    "LocalCommandApplicationResult",
    "LocalCommandApplicationRoute",
    "LocalCommandProjection",
    "LocalCommandProjectionKind",
    "LocalKnowledgeFindProjection",
    "LocalKnowledgeProjection",
    "LocalKnowledgeProjectionOperation",
    "LocalKnowledgeReadProjection",
    "LocalKnowledgeRecordKind",
    "LocalKnowledgeRecordProjection",
    "LocalKnowledgeStoreProjection",
    "LocalListAddProjection",
    "LocalListProjection",
    "LocalListProjectionOperation",
    "LocalListReadProjection",
    "application_error",
]
